spring:
  application:
    name: eureka-service
  security:
    basic:
     enabled: true
    user:
      name: root
      password: root

server:
  port: 9999



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
     defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 172.16.1.252


